name: Trial Run planet.py

on:
  workflow_dispatch:   # manual run option
  schedule:
    # Trial run at 6:45 PM IST (13:15 UTC) + every 5 minutes, 6 cycles
    - cron: "15 13 * * *"
    - cron: "20 13 * * *"
    - cron: "25 13 * * *"
    - cron: "30 13 * * *"
    - cron: "35 13 * * *"
    - cron: "40 13 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run planet.py
        run: python planet.py
