name: Planet.py Trial - 6 Cycles 5min Interval

on:
  workflow_dispatch:   # manual run option
  schedule:
    # 7:45 PM IST = 14:15 UTC
    - cron: "15 14 * * *"  # Cycle 1
    - cron: "20 14 * * *"  # Cycle 2
    - cron: "25 14 * * *"  # Cycle 3
    - cron: "30 14 * * *"  # Cycle 4
    - cron: "35 14 * * *"  # Cycle 5
    - cron: "40 14 * * *"  # Cycle 6

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run planet.py
        run: python planet.py
